version: "3.9"

services:

  postgres:
    image: postgres:16.2
    environment:
      POSTGRES_DB: "name_db"
      POSTGRES_USER: "user_db"
      POSTGRES_PASSWORD: "passwords"
    ports:
      - "5432:5432"
